services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    volumes:
      - /docker_data/postgres:/var/lib/postgresql/data
      - /docker_data/postgres_sql:/home/postgres_sql

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
